_BASE_: "../../FCOS-Detection/Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  RESIZER:
    WEIGHTS: "../weights/pretrained/resnet/resizer-R-18.pkl"
    ENCODER:
      NAME: "build_resnet_backbone"
      DEPTH: 18
      RES2_OUT_CHANNELS: 64
SOLVER:
  MAX_ITER: 180000
  BASE_LR_END: 5e-5
  LR_SCHEDULER_NAME: "WarmupConstCosineLR"
OUTPUT_DIR: "output/dyra/FCOS_R_50_2x"
