_BASE_: "../../FCOS-Detection/Base-FCOS.yaml"
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 800
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    NORM: "BN"
  FCOS:
    TOP_LEVELS: 0
    SIZES_OF_INTEREST: [32]
    FPN_STRIDES: [8, 16]
    IN_FEATURES: ['p3', 'p4']
    NORM: "BN"
  RESIZER:
    WEIGHTS: "../wegihts/pretrained/resnet/resizer-R-18.pkl"
    ENCODER:
      NAME: "build_resnet_backbone"
      DEPTH: 18
      RES2_OUT_CHANNELS: 64
SOLVER:
  MAX_ITER: 360000
  BASE_LR_END: 5e-5
  LR_SCHEDULER_NAME: "WarmupConstCosineLR"
OUTPUT_DIR: "output/fcos/FCOS_RT_MS_R_50_4x_syncbn_bn_head"
