_BASE_: "../../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
  RESIZER:
    WEIGHTS: "../weights/pretrained/resnet/resizer-R-18.pkl"
    ENCODER:
      NAME: "build_resnet_backbone"
      DEPTH: 18
      RES2_OUT_CHANNELS: 64
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  BASE_LR_END: 5e-5
  LR_SCHEDULER_NAME: "WarmupConstCosineLR"
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
